### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AIPTU** [Muqsit/DeathInventoryLog#3]
Fatal error: Uncaught Error: Call to undefined method muqsit\deathinventorylog\libs\pog
git\libasynql\sqlite3\Sqlite3Thread::registerClassLoader() in phar:///root/aiptu/Pocket
Mine-MP/master/server/plugins/DeathInventoryLog_dev-9.phar/src/muqsit/deathinventorylog
/libs/poggit/libasynql/base/SqlSlaveThread.php:68                                      
Stack trace:                                                                           
#0 phar:///root/aiptu/PocketMine-MP/master/server/PocketMine-MP.phar/src/thread/CommonT
hreadPartsTrait.php(93): muqsit\deathinventorylog\libs\poggit\libasynql\base\SqlSlaveTh
read->onRun()                                                                          
#1 [internal function]: pocketmine\thread\Thread->run()                                
#2 {main}                                                                              
  thrown in phar:///root/aiptu/PocketMine-MP/master/server/plugins/DeathInventoryLog_de
v-9.phar/src/muqsit/deathinventorylog/libs/poggit/libasynql/base/SqlSlaveThread.php on line 68

**Comment by Muqsit** [comment]
This is an issue with libasynql (https://github.com/poggit/libasynql/issues/62).

**Comment by AIPTU** [comment]
how to solve this issue?, Pre compile plugin?

**Comment by Muqsit** [comment]
poggit/libasynql just pushed a fix for this issue, the [DeathInventoryLog_dev-10.phar](https://poggit.pmmp.io/r/132561/DeathInventoryLog_dev-10.phar) file generated by the latest commit 26d3d908ec8c0501a8f4955568c57294a9b1fa3a shouldn't throw the above error.
