### ISSUE TITLE
Updated Vers of InvMenu

### ISSUE THREAD

**Issue by XyloFD2** [Muqsit/DeathInventoryLog#5]
[16:21:13.694] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\mcpe\InventoryManager::getWindow()" (EXCEPTION) in "plugins/DeathInventoryLog.phar/src/muqsit/deathinventorylog/libs/muqsit/invmenu/session/network/PlayerNetwork" at line 165
--- Stack trace ---
  #0 plugins/DeathInventoryLog.phar/src/muqsit/deathinventorylog/libs/muqsit/invmenu/InvMenuEventHandler(64): muqsit\deathinventorylog\libs\muqsit\invmenu\session\network\PlayerNetwork->translateContainerOpen(object muqsit\deathinventorylog\libs\muqsit\invmenu\session\PlayerSession#424569, object pocketmine\network\mcpe\protocol\ContainerOpenPacket#482224)
  #1 pmsrc/src/event/RegisteredListener(60): muqsit\deathinventorylog\libs\muqsit\invmenu\InvMenuEventHandler->onDataPacketSend(object pocketmine\event\server\DataPacketSendEvent#482392)
  #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#482392)
  #3 pmsrc/src/network/mcpe/NetworkSession(436): pocketmine\event\Event->call()
  #4 pmsrc/src/network/mcpe/InventoryManager(312): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\ContainerOpenPacket#482224)
  #5 pmsrc/src/network/mcpe/InventoryManager(227): pocketmine\network\mcpe\InventoryManager->pocketmine\network\mcpe\{closure}()
  #6 pmsrc/src/network/mcpe/InventoryManager(314): pocketmine\network\mcpe\InventoryManager->openWindowDeferred(object Closure#482372)
  #7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(562): pocketmine\network\mcpe\InventoryManager->onClientOpenMainInventory()
  #8 pmsrc/vendor/pocketmine/bedrock-protocol/src/InteractPacket(57): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInteract(object pocketmine\network\mcpe\protocol\InteractPacket#482581)
  #9 pmsrc/src/network/mcpe/NetworkSession(418): pocketmine\network\mcpe\protocol\InteractPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#456183)
  #10 pmsrc/src/network/mcpe/NetworkSession(374): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InteractPacket#482581, string[3] !..)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(183): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[6] cVdc..)
  #12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[15] .n^...'.....C<.)
  #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(113): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#428734)
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #16 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1671985273.6789)
  #17 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
  #18 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #19 pmsrc/src/PocketMine(362): pocketmine\server()
  #20 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by Muqsit** [comment]
You may use the upcoming release build until then: https://poggit.pmmp.io/r/198493/DeathInventoryLog_dev-29.phar
